/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste les catégories du foyer de l'appelant (disponibles immédiatement pour le formulaire). */
        get: operations["listCategories"];
        put?: never;
        /**
         * Crée une catégorie dans le foyer de l'appelant. **Idempotent** via l'en-tête `Idempotency-Key`
         *     (REQ-SYN-006) : un rejeu à clé + corps identiques renvoie la réponse initiale sans nouvelle création.
         */
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Renomme une catégorie du foyer de l'appelant. */
        put: operations["renameCategory"];
        post?: never;
        /**
         * Supprime une catégorie du foyer de l'appelant.
         * @description Refuse la suppression d'une catégorie **référencée** par un abonnement (`409`, REQ-CAT-003 :
         *     comportement capturé sur l'application d'origine, jamais de réaffectation ni de cascade).
         */
        delete: operations["deleteCategory"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/currencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste les devises supportées (code, symbole, libellé, décimales), pour l'interface. */
        get: operations["listCurrencies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/device-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Appaire un appareil natif et émet un jeton propre à l'appareil (REQ-AUT-005). */
        post: operations["createDeviceSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste les appareils appairés du foyer courant, en distinguant l'appareil courant (REQ-AUT-006). */
        get: operations["listDevices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Révoque un appareil appairé — révocation **immédiate** : son jeton ne vaut plus rien (REQ-AUT-006). */
        delete: operations["revokeDevice"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exchange/aggregate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Agrège des montants multi-devises vers une devise cible, en **mode dégradé** explicite
         *     (REQ-CUR-004).
         * @description La table de taux est reconstruite depuis les **derniers taux connus** persistés
         *     ([`load_rate_table`]) : sans fournisseur configuré (ou s'il est indisponible), l'app reste
         *     fonctionnelle et retombe sur ces taux. Chaque montant sans taux est **exclu** et l'agrégat est
         *     signalé incomplet (`complete = false`), jamais présenté comme un zéro silencieux ; `as_of` porte
         *     la fraîcheur (date du taux le plus ancien utilisé) que l'interface doit afficher.
         */
        post: operations["aggregateConverted"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** État de santé du serveur. */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Renvoie le compte authentifié courant. */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Change le mot de passe du compte courant et coupe les accès existants (REQ-AUT-007).
         * @description Exige le mot de passe actuel (sinon `403`, aucun état modifié). Le nouveau doit respecter la
         *     politique (REQ-AUT-003, sinon `422`). En cas de succès, **toutes les sessions et jetons
         *     d'appareil sont invalidés sauf la crédential courante** — un changement de mot de passe qui ne
         *     couperait pas les accès existants ne remédierait à rien.
         */
        put: operations["changePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payment-methods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste les moyens de paiement du foyer de l'appelant. */
        get: operations["listPaymentMethods"];
        put?: never;
        /**
         * Crée un moyen de paiement dans le foyer de l'appelant. **Idempotent** via `Idempotency-Key`
         *     (REQ-SYN-006).
         */
        post: operations["createPaymentMethod"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payment-methods/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Renomme un moyen de paiement du foyer de l'appelant. */
        put: operations["renamePaymentMethod"];
        post?: never;
        /** Supprime un moyen de paiement du foyer de l'appelant. */
        delete: operations["deletePaymentMethod"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule/next-due": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calcule la prochaine échéance strictement postérieure à `after`, pour l'ancre et le cycle donnés. */
        post: operations["computeNextDue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authentifie un utilisateur et ouvre une session web (cookie). */
        post: operations["createSession"];
        /**
         * Déconnecte : invalide la session côté serveur et expire le cookie (REQ-AUT-009).
         * @description **Idempotent** : renvoie toujours `204`, même sans cookie ou session déjà invalidée.
         */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/language": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lit la langue de l'utilisateur appelant (absente si non renseignée). */
        get: operations["getLanguage"];
        /** Fixe la langue de l'utilisateur appelant. */
        put: operations["setLanguage"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/reference-currency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lit la devise de référence du foyer de l'appelant. */
        get: operations["getReferenceCurrency"];
        /** Fixe la devise de référence du foyer de l'appelant. */
        put: operations["setReferenceCurrency"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste les abonnements du foyer, filtrés (conjonctifs), avec le total agrégé du sous-ensemble actif. */
        get: operations["listSubscriptions"];
        put?: never;
        /**
         * Crée un abonnement dans le foyer de l'appelant ; renvoie l'abonnement et sa prochaine échéance.
         *     **Idempotent** via `Idempotency-Key` (REQ-SYN-006).
         */
        post: operations["createSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Modifie un abonnement du foyer de l'appelant ; recalcule la prochaine échéance (REQ-SUB-004).
         * @description L'échéance est **ré-ancrée sur `first_payment`** avec le nouveau cycle (jamais dérivée de
         *     l'ancienne). La résolution des modifications concurrentes (horodatage antérieur) relève de
         *     REQ-SYN-005, hors de ce vertical : ici, la dernière écriture reçue fait foi.
         */
        put: operations["updateSubscription"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Requête d'agrégation multi-devises vers une devise cible (REQ-CUR-004). */
        AggregateRequest: {
            /** @description Montants à convertir puis sommer. */
            amounts: components["schemas"]["MoneyInput"][];
            /**
             * @description Devise cible de l'agrégat (code ISO 4217).
             * @example EUR
             */
            target: string;
        };
        /**
         * @description Cycle de facturation d'un abonnement (REQ-SUB-003) : couple (unité, intervalle).
         *
         *     `unit` est un code stable (`day`/`week`/`month`/`year`) ; `interval` est le nombre d'unités entre
         *     deux échéances, strictement positif. Modèle capturé sur l'application d'origine (table `cycles`).
         */
        BillingCycleDto: {
            /**
             * Format: int32
             * @description Nombre d'unités entre deux échéances (strictement positif).
             * @example 1
             */
            interval: number;
            /**
             * @description Unité de récurrence : `day`, `week`, `month` ou `year`.
             * @example month
             */
            unit: string;
        };
        /** @description Une catégorie d'abonnements exposée à l'interface (REQ-CAT-001). */
        CategoryDto: {
            /** @description Identifiant stable (UUID). */
            id: string;
            /**
             * @description Nom de la catégorie.
             * @example Streaming
             */
            name: string;
        };
        /**
         * @description Requête de changement de mot de passe (REQ-AUT-007).
         *
         *     Exige le mot de passe actuel (sinon `403`) ; le nouveau doit respecter la politique (REQ-AUT-003).
         */
        ChangePasswordRequest: {
            /**
             * Format: password
             * @description Mot de passe actuel, revérifié côté serveur.
             */
            current_password: string;
            /**
             * Format: password
             * @description Nouveau mot de passe (longueur minimale + non compromis, REQ-AUT-003).
             */
            new_password: string;
        };
        /**
         * @description Résultat d'une agrégation convertie, en **mode dégradé** explicite (REQ-CUR-004).
         *
         *     `total` est une chaîne décimale (R4). `complete` est faux dès qu'un montant a été **exclu** faute
         *     de taux : un total incomplet n'est jamais présenté comme un zéro silencieux. `as_of` porte la
         *     date de validité **la plus ancienne** parmi les taux utilisés — la fraîcheur à afficher quand le
         *     fournisseur est indisponible et que l'on retombe sur le dernier taux connu.
         */
        ConvertedTotalResponse: {
            /**
             * @description Date de validité la plus ancienne des taux utilisés (`YYYY-MM-DD`), ou absente si aucun taux
             *     daté n'a servi (ensemble vide ou conversions en devise identique uniquement).
             * @example 2026-07-20
             */
            as_of?: string | null;
            /** @description Vrai si tous les montants ont pu être convertis (agrégat complet). */
            complete: boolean;
            /**
             * Format: int32
             * @description Nombre de montants effectivement convertis et inclus.
             */
            converted: number;
            /**
             * @description Devise du total (code ISO 4217).
             * @example EUR
             */
            currency: string;
            /**
             * Format: int32
             * @description Nombre de montants exclus faute de taux connu.
             */
            excluded: number;
            /**
             * @description Total converti dans la devise cible (chaîne décimale, précision exacte).
             * @example 142.50
             */
            total: string;
        };
        /**
         * @description Requête de création de compte (REQ-AUT-001).
         *
         *     Le mot de passe transite en clair sur le canal TLS puis est haché argon2id côté serveur ;
         *     il n'est jamais stocké en clair.
         */
        CreateAccountRequest: {
            /**
             * Format: email
             * @description Adresse e-mail du compte.
             * @example user@example.com
             */
            email: string;
            /**
             * @description Langue choisie à l'inscription (REQ-I18N-001), code court `en`/`fr`. Optionnelle : si absente,
             *     le compte n'a pas de langue explicite (repli langue système côté UI) et le jeu de catégories
             *     par défaut (REQ-CAT-002) est semé en anglais. Un code non supporté est refusé (422).
             * @example fr
             */
            language?: string | null;
            /**
             * Format: password
             * @description Mot de passe (longueur minimale vérifiée côté serveur, REQ-AUT-003).
             * @example correct horse battery staple
             */
            password: string;
        };
        /** @description Requête de création d'une catégorie (REQ-CAT-001). */
        CreateCategoryRequest: {
            /**
             * @description Identifiant (UUID) **généré côté client** (offline-first, REQ-SYN-001), le cas échéant. Absent
             *     ⇒ le serveur en génère un. Présent ⇒ il est **conservé tel quel**.
             */
            id?: string | null;
            /**
             * @description Nom de la catégorie (non vide, ≤ 100 caractères ; les espaces de bord sont normalisés).
             * @example Streaming
             */
            name: string;
        };
        /**
         * @description Requête d'appairage d'un appareil natif (REQ-AUT-005).
         *
         *     Comme l'authentification web, mais émet un jeton propre à l'appareil (corps de réponse) au lieu
         *     d'un cookie ; l'appareil fournit un libellé et sa plateforme.
         */
        CreateDeviceSessionRequest: {
            /**
             * Format: email
             * @description Adresse e-mail du compte.
             * @example user@example.com
             */
            email: string;
            /**
             * @description Libellé lisible de l'appareil (choisi par l'utilisateur ou dérivé du matériel).
             * @example MacBook de Léa
             */
            label: string;
            /**
             * Format: password
             * @description Mot de passe.
             */
            password: string;
            /**
             * @description Plateforme de l'appareil.
             * @example desktop
             */
            platform: string;
        };
        /** @description Requête de création d'un moyen de paiement (REQ-SUB-011). */
        CreatePaymentMethodRequest: {
            /**
             * @description Identifiant (UUID) **généré côté client** (offline-first, REQ-SYN-001), le cas échéant. Absent
             *     ⇒ le serveur en génère un. Présent ⇒ il est **conservé tel quel**.
             */
            id?: string | null;
            /**
             * @description Nom (non vide, ≤ 100 caractères ; les espaces de bord sont normalisés).
             * @example Carte de crédit
             */
            name: string;
        };
        /** @description Requête d'authentification (REQ-AUT-002). */
        CreateSessionRequest: {
            /**
             * Format: email
             * @description Adresse e-mail du compte.
             * @example user@example.com
             */
            email: string;
            /**
             * Format: password
             * @description Mot de passe.
             */
            password: string;
        };
        /**
         * @description Requête de création d'un abonnement (REQ-SUB-002). Mêmes champs que [`SubscriptionDto`] sans `id`
         *     (généré par le serveur) ni `next_payment` (dérivé). Montant en **chaîne** décimale (R4).
         */
        CreateSubscriptionRequest: {
            /** @description État actif (défaut : actif). */
            active?: boolean;
            /**
             * @description Montant du prix (chaîne décimale).
             * @example 9.99
             */
            amount: string;
            /** @description Catégorie rattachée (UUID), le cas échéant. */
            category?: string | null;
            /**
             * @description Code devise ISO 4217.
             * @example EUR
             */
            currency: string;
            /** @description Cycle de facturation. */
            cycle: components["schemas"]["BillingCycleDto"];
            /** @description Date de fin (annulation programmée, `YYYY-MM-DD`, REQ-SUB-009), le cas échéant. */
            end_date?: string | null;
            /**
             * @description Date de premier paiement (`YYYY-MM-DD`).
             * @example 2025-01-31
             */
            first_payment: string;
            /**
             * @description Identifiant (UUID) **généré côté client** (offline-first, REQ-SYN-001), le cas échéant. Absent
             *     ⇒ le serveur en génère un. Présent ⇒ il est **conservé tel quel**.
             */
            id?: string | null;
            /** @description Logo, le cas échéant. */
            logo?: string | null;
            /** @description Nom de l'abonnement. */
            name: string;
            /** @description Notes libres, le cas échéant. */
            notes?: string | null;
            /** @description Payeur rattaché (UUID), le cas échéant. */
            payer?: string | null;
            /** @description Moyen de paiement rattaché (UUID), le cas échéant. */
            payment_method?: string | null;
            /** @description URL du service, le cas échéant. */
            url?: string | null;
        };
        /**
         * @description Une devise du référentiel supporté exposée à l'interface (REQ-CUR-007).
         *
         *     `name` est le libellé par défaut (anglais) ; l'UI affiche le nom **localisé** par code (i18n).
         */
        CurrencyDto: {
            /**
             * @description Code ISO 4217.
             * @example EUR
             */
            code: string;
            /**
             * Format: int32
             * @description Nombre de décimales d'affichage (unités mineures ISO 4217).
             * @example 2
             */
            decimals: number;
            /**
             * @description Libellé par défaut (localisé par l'UI).
             * @example Euro
             */
            name: string;
            /**
             * @description Symbole d'affichage.
             * @example €
             */
            symbol: string;
        };
        /** @description Représentation du compte authentifié courant (REQ-AUT-002). */
        CurrentUser: {
            /** @description Adresse e-mail du compte courant. */
            email: string;
        };
        /**
         * @description Résumé d'un appareil appairé, pour la liste de gestion (REQ-AUT-006).
         *
         *     `id` (UUID) et `last_seen_at` (RFC 3339) sont sérialisés en chaînes pour rester indépendants des
         *     features `utoipa`/`chrono` ; `current` distingue l'appareil à l'origine de la requête courante.
         */
        DeviceSummary: {
            /** @description Vrai si cet appareil est celui qui a émis la requête courante. */
            current: boolean;
            /** @description Identifiant de l'appareil (UUID), clé de révocation. */
            id: string;
            /** @description Libellé lisible. */
            label: string;
            /** @description Dernière activité (horodatage RFC 3339). */
            last_seen_at: string;
            /** @description Plateforme de l'appareil. */
            platform: string;
        };
        /**
         * @description Jeton d'appareil émis à l'appairage (REQ-AUT-005).
         *
         *     Renvoyé **une seule fois** : la coquille native le stocke via `PlatformAdapter.secureStore`,
         *     jamais en clair côté serveur (seule son empreinte SHA-256 est conservée).
         */
        DeviceToken: {
            /** @description Jeton opaque à présenter en `Authorization: Bearer`. */
            token: string;
        };
        /** @description Réponse d'état du serveur. */
        HealthResponse: {
            /** @description Nom du service. */
            service: string;
            /** @description État. */
            status: string;
            /** @description Version semver. */
            version: string;
        };
        /**
         * @description Langue de l'utilisateur (REQ-I18N-001), en **réponse** de lecture.
         *
         *     `language` est absent (`None`) si l'utilisateur n'a rien choisi : l'UI applique alors la langue
         *     système si elle est supportée (acceptance #2).
         */
        LanguageResponse: {
            /**
             * @description Code de langue (`en`, `fr`), ou absent si non renseigné.
             * @example fr
             */
            language?: string | null;
        };
        /**
         * @description Un montant en devise pour l'agrégation multi-devises (REQ-CUR-004).
         *
         *     `amount` est une **chaîne décimale** (règle R4 / REQ-CUR-002) : jamais un nombre JSON, qui
         *     introduirait une imprécision flottante sur un montant.
         */
        MoneyInput: {
            /**
             * @description Montant en chaîne décimale (ex. `"12.34"`).
             * @example 12.34
             */
            amount: string;
            /**
             * @description Code devise ISO 4217 (ex. `"EUR"`).
             * @example EUR
             */
            currency: string;
        };
        /**
         * @description Requête de calcul de la prochaine échéance (REQ-SUB-012).
         *
         *     `first_payment` est l'**ancre** (date de premier paiement) ; `after` est la date de référence — la
         *     réponse est la première échéance strictement postérieure. Dates en `YYYY-MM-DD`.
         */
        NextDueRequest: {
            /**
             * @description Date de référence : la prochaine échéance est strictement postérieure, `YYYY-MM-DD`.
             * @example 2025-01-31
             */
            after: string;
            /** @description Cycle de facturation. */
            cycle: components["schemas"]["BillingCycleDto"];
            /**
             * @description Date de premier paiement (ancre), `YYYY-MM-DD`.
             * @example 2025-01-31
             */
            first_payment: string;
        };
        /** @description Prochaine échéance calculée (REQ-SUB-012). */
        NextDueResponse: {
            /**
             * @description Prochaine échéance, `YYYY-MM-DD`.
             * @example 2025-02-28
             */
            next_payment: string;
        };
        /** @description Un moyen de paiement exposé à l'interface (REQ-SUB-011). */
        PaymentMethodDto: {
            /** @description Identifiant stable (UUID). */
            id: string;
            /**
             * @description Nom du moyen de paiement.
             * @example Carte de crédit
             */
            name: string;
        };
        /**
         * @description Détail d'erreur conforme à la RFC 9457 (`application/problem+json`).
         *
         *     Schéma d'erreur unique de l'API : toute réponse d'erreur adopte ce format,
         *     sans jamais divulguer de trace d'exécution, de requête SQL ni de chemin de
         *     fichier (AGENTS.md §6, REQ-SEC-002).
         */
        Problem: {
            /** @description Explication spécifique à cette occurrence du problème. */
            detail?: string | null;
            /** @description URI de référence identifiant l'occurrence spécifique du problème. */
            instance?: string | null;
            /**
             * Format: int32
             * @description Code de statut HTTP généré par l'origine.
             */
            status: number;
            /** @description Résumé court et lisible du type de problème, stable pour un `type` donné. */
            title: string;
            /**
             * @description URI de référence identifiant le type de problème.
             * @example about:blank
             */
            type: string;
        };
        /**
         * @description Devise de référence du foyer (REQ-CUR-001) : devise cible de tous les agrégats.
         *
         *     Sert à la fois de **réponse** (`GET`) et de **corps de requête** (`PUT`). Le code est validé contre
         *     le référentiel supporté côté serveur ; les montants saisis ne sont jamais altérés.
         */
        ReferenceCurrencyDto: {
            /**
             * @description Code ISO 4217 de la devise de référence.
             * @example EUR
             */
            currency: string;
        };
        /** @description Requête de renommage d'une catégorie (REQ-CAT-001). */
        RenameCategoryRequest: {
            /**
             * @description Nouveau nom de la catégorie (non vide, ≤ 100 caractères ; espaces de bord normalisés).
             * @example Musique
             */
            name: string;
        };
        /** @description Requête de renommage d'un moyen de paiement (REQ-SUB-011). */
        RenamePaymentMethodRequest: {
            /**
             * @description Nouveau nom (non vide, ≤ 100 caractères ; espaces de bord normalisés).
             * @example PayPal
             */
            name: string;
        };
        /** @description Requête de choix de langue (REQ-I18N-001) : le code doit être une langue supportée. */
        SetLanguageRequest: {
            /**
             * @description Code de langue souhaité (`en`, `fr`).
             * @example fr
             */
            language: string;
        };
        /**
         * @description Représentation d'un abonnement dans le contrat API (REQ-SUB-001).
         *
         *     Reflet 1:1 du modèle [`Subscription`] du domaine : aucun champ n'est perdu ni normalisé
         *     silencieusement. Montant en **chaîne** décimale (R4/CUR-002) ; identifiants et date en chaînes
         *     (indépendants des features `utoipa`) ; cycle imbriqué (REQ-SUB-003).
         */
        SubscriptionDto: {
            /**
             * @description État actif (un abonnement désactivé est conservé mais exclu des agrégats, REQ-SUB-008).
             *     Absent à la désérialisation ⇒ actif par défaut, aligné sur le domaine (`Subscription::new`).
             */
            active?: boolean;
            /**
             * @description Montant du prix (chaîne décimale).
             * @example 9.99
             */
            amount: string;
            /** @description Catégorie rattachée (UUID), le cas échéant. */
            category?: string | null;
            /**
             * @description Code devise ISO 4217 du prix.
             * @example EUR
             */
            currency: string;
            /** @description Cycle de facturation. */
            cycle: components["schemas"]["BillingCycleDto"];
            /** @description Date de fin (annulation programmée, `YYYY-MM-DD`, REQ-SUB-009), le cas échéant. */
            end_date?: string | null;
            /**
             * @description Vrai si l'abonnement est **terminé** (date de fin dépassée) — champ **dérivé** (horloge serveur),
             *     REQ-SUB-009. Un abonnement terminé est conservé mais exclu des agrégats.
             */
            ended?: boolean;
            /**
             * @description Date de premier paiement (`YYYY-MM-DD`).
             * @example 2026-01-31
             */
            first_payment: string;
            /** @description Identifiant stable (UUID). */
            id: string;
            /** @description Logo (référence d'image ou substitut), le cas échéant. */
            logo?: string | null;
            /**
             * @description Coût **mensuel normalisé** (chaîne décimale, REQ-STA-001), dans la devise de l'abonnement.
             *     Champ **dérivé** : facteur de cycle capturé sur l'application d'origine (30 j/mois, 4.35 sem/mois,
             *     12 mois/an). L'arrondi d'affichage relève de REQ-CUR-005.
             */
            monthly_cost?: string;
            /** @description Nom de l'abonnement. */
            name: string;
            /**
             * @description Prochaine échéance calculée (`YYYY-MM-DD`, REQ-SUB-002/012), champ **dérivé** : présent dans les
             *     réponses de lecture/création, absent du modèle pur (calculé avec l'horloge serveur).
             */
            next_payment?: string | null;
            /** @description Notes libres, le cas échéant. */
            notes?: string | null;
            /** @description Payeur rattaché (UUID), le cas échéant. */
            payer?: string | null;
            /** @description Moyen de paiement rattaché (UUID), le cas échéant. */
            payment_method?: string | null;
            /** @description URL du service, le cas échéant. */
            url?: string | null;
            /**
             * @description Coût **annuel normalisé** (chaîne décimale, REQ-STA-002), dans la devise de l'abonnement.
             *     Champ **dérivé** : `annuel = mensuel × 12` (relation capturée sur l'application d'origine — les
             *     deux indicateurs ne divergent jamais).
             */
            yearly_cost?: string;
        };
        /**
         * @description Liste d'abonnements filtrée avec son **total agrégé** (REQ-SUB-006).
         *
         *     Le `total` reflète le filtre : il agrège les montants des abonnements **actifs** retournés,
         *     convertis dans la devise cible (réutilise l'agrégat multi-devises en mode dégradé, REQ-CUR-004) —
         *     un abonnement désactivé est exclu du total (REQ-SUB-008) même s'il figure dans la liste.
         */
        SubscriptionListResponse: {
            /** @description Abonnements du foyer correspondant au filtre (ordre stable : nom puis id). */
            subscriptions: components["schemas"]["SubscriptionDto"][];
            /** @description Total agrégé des abonnements actifs de la liste, dans la devise cible. */
            total: components["schemas"]["ConvertedTotalResponse"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountRequest"];
            };
        };
        responses: {
            /** @description Compte créé — réponse identique que l'e-mail existe ou non */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Requête invalide (politique de mot de passe ou langue non supportée) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Erreur interne (hachage ou base de données) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Catégories du foyer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryDto"][];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header?: {
                /** @description Clé d'idempotence (REQ-SYN-006) */
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryRequest"];
            };
        };
        responses: {
            /** @description Catégorie créée */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryDto"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflit : identifiant déjà utilisé, ou clé d'idempotence réutilisée avec un corps différent */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Identifiant ou nom invalide */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    renameCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant (UUID) de la catégorie */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameCategoryRequest"];
            };
        };
        responses: {
            /** @description Catégorie renommée */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryDto"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Catégorie inconnue ou hors du foyer */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Nom invalide */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    deleteCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant (UUID) de la catégorie */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Catégorie supprimée */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Catégorie inconnue ou hors du foyer */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Catégorie référencée par un abonnement : suppression refusée */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listCurrencies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Référentiel des devises supportées */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrencyDto"][];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    createDeviceSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDeviceSessionRequest"];
            };
        };
        responses: {
            /** @description Appareil appairé ; jeton d'appareil émis (corps) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceToken"];
                };
            };
            /** @description Identifiants invalides */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Trop de tentatives ; réessayer après l'en-tête Retry-After */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listDevices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Appareils appairés du foyer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceSummary"][];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    revokeDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant (UUID) de l'appareil à révoquer */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Appareil révoqué */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Appareil inconnu ou hors du foyer */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    aggregateConverted: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AggregateRequest"];
            };
        };
        responses: {
            /** @description Agrégat converti (éventuellement partiel) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConvertedTotalResponse"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Devise ou montant invalide */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Serveur opérationnel */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Compte courant */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Mot de passe changé ; autres sessions et jetons d'appareil invalidés */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Mot de passe actuel incorrect ; aucun changement */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Nouveau mot de passe non conforme */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Trop de tentatives ; réessayer après l'en-tête Retry-After */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listPaymentMethods: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Moyens de paiement du foyer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentMethodDto"][];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    createPaymentMethod: {
        parameters: {
            query?: never;
            header?: {
                /** @description Clé d'idempotence (REQ-SYN-006) */
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePaymentMethodRequest"];
            };
        };
        responses: {
            /** @description Moyen de paiement créé */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentMethodDto"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflit : identifiant déjà utilisé, ou clé d'idempotence réutilisée avec un corps différent */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Identifiant ou nom invalide */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    renamePaymentMethod: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant (UUID) du moyen de paiement */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenamePaymentMethodRequest"];
            };
        };
        responses: {
            /** @description Moyen de paiement renommé */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentMethodDto"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Inconnu ou hors du foyer */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Nom invalide */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    deletePaymentMethod: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant (UUID) du moyen de paiement */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Moyen de paiement supprimé */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Inconnu ou hors du foyer */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    computeNextDue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NextDueRequest"];
            };
        };
        responses: {
            /** @description Prochaine échéance */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NextDueResponse"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Entrée invalide */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Session ouverte ; cookie de session posé */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Identifiants invalides */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Trop de tentatives ; réessayer après l'en-tête Retry-After */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session invalidée (idempotent) ; cookie expiré */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getLanguage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Langue de l'utilisateur (ou absente) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LanguageResponse"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    setLanguage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetLanguageRequest"];
            };
        };
        responses: {
            /** @description Langue mise à jour */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LanguageResponse"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Langue non supportée */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getReferenceCurrency: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Devise de référence du foyer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceCurrencyDto"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    setReferenceCurrency: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReferenceCurrencyDto"];
            };
        };
        responses: {
            /** @description Devise de référence mise à jour */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceCurrencyDto"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Devise hors référentiel */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listSubscriptions: {
        parameters: {
            query?: {
                /** @description Restreint à une catégorie (UUID). */
                category?: string;
                /** @description Restreint à un payeur (UUID). */
                payer?: string;
                /** @description Restreint à l'état actif (`true`) ou inactif (`false`). */
                active?: boolean;
                /**
                 * @description Devise cible du total agrégé (code ISO 4217 ; défaut `EUR`).
                 * @example EUR
                 */
                currency?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Abonnements filtrés et total agrégé */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionListResponse"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Filtre invalide */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    createSubscription: {
        parameters: {
            query?: never;
            header?: {
                /** @description Clé d'idempotence (REQ-SYN-006) */
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSubscriptionRequest"];
            };
        };
        responses: {
            /** @description Abonnement créé (avec prochaine échéance) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionDto"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflit : identifiant déjà utilisé, ou clé d'idempotence réutilisée avec un corps différent */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation par champ (dont identifiant) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    updateSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant (UUID) de l'abonnement */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSubscriptionRequest"];
            };
        };
        responses: {
            /** @description Abonnement modifié (échéance recalculée) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionDto"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Abonnement inconnu ou hors du foyer */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation par champ */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
