/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crée un compte utilisateur. */
        post: operations["createAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/device-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Appaire un appareil natif et émet un jeton propre à l'appareil (REQ-AUT-005). */
        post: operations["createDeviceSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste les appareils appairés du foyer courant, en distinguant l'appareil courant (REQ-AUT-006). */
        get: operations["listDevices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Révoque un appareil appairé — révocation **immédiate** : son jeton ne vaut plus rien (REQ-AUT-006). */
        delete: operations["revokeDevice"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exchange/aggregate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Agrège des montants multi-devises vers une devise cible, en **mode dégradé** explicite
         *     (REQ-CUR-004).
         * @description La table de taux est reconstruite depuis les **derniers taux connus** persistés
         *     ([`load_rate_table`]) : sans fournisseur configuré (ou s'il est indisponible), l'app reste
         *     fonctionnelle et retombe sur ces taux. Chaque montant sans taux est **exclu** et l'agrégat est
         *     signalé incomplet (`complete = false`), jamais présenté comme un zéro silencieux ; `as_of` porte
         *     la fraîcheur (date du taux le plus ancien utilisé) que l'interface doit afficher.
         */
        post: operations["aggregateConverted"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** État de santé du serveur. */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Renvoie le compte authentifié courant. */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Change le mot de passe du compte courant et coupe les accès existants (REQ-AUT-007).
         * @description Exige le mot de passe actuel (sinon `403`, aucun état modifié). Le nouveau doit respecter la
         *     politique (REQ-AUT-003, sinon `422`). En cas de succès, **toutes les sessions et jetons
         *     d'appareil sont invalidés sauf la crédential courante** — un changement de mot de passe qui ne
         *     couperait pas les accès existants ne remédierait à rien.
         */
        put: operations["changePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authentifie un utilisateur et ouvre une session web (cookie). */
        post: operations["createSession"];
        /**
         * Déconnecte : invalide la session côté serveur et expire le cookie (REQ-AUT-009).
         * @description **Idempotent** : renvoie toujours `204`, même sans cookie ou session déjà invalidée.
         */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Requête d'agrégation multi-devises vers une devise cible (REQ-CUR-004). */
        AggregateRequest: {
            /** @description Montants à convertir puis sommer. */
            amounts: components["schemas"]["MoneyInput"][];
            /**
             * @description Devise cible de l'agrégat (code ISO 4217).
             * @example EUR
             */
            target: string;
        };
        /**
         * @description Requête de changement de mot de passe (REQ-AUT-007).
         *
         *     Exige le mot de passe actuel (sinon `403`) ; le nouveau doit respecter la politique (REQ-AUT-003).
         */
        ChangePasswordRequest: {
            /**
             * Format: password
             * @description Mot de passe actuel, revérifié côté serveur.
             */
            current_password: string;
            /**
             * Format: password
             * @description Nouveau mot de passe (longueur minimale + non compromis, REQ-AUT-003).
             */
            new_password: string;
        };
        /**
         * @description Résultat d'une agrégation convertie, en **mode dégradé** explicite (REQ-CUR-004).
         *
         *     `total` est une chaîne décimale (R4). `complete` est faux dès qu'un montant a été **exclu** faute
         *     de taux : un total incomplet n'est jamais présenté comme un zéro silencieux. `as_of` porte la
         *     date de validité **la plus ancienne** parmi les taux utilisés — la fraîcheur à afficher quand le
         *     fournisseur est indisponible et que l'on retombe sur le dernier taux connu.
         */
        ConvertedTotalResponse: {
            /**
             * @description Date de validité la plus ancienne des taux utilisés (`YYYY-MM-DD`), ou absente si aucun taux
             *     daté n'a servi (ensemble vide ou conversions en devise identique uniquement).
             * @example 2026-07-20
             */
            as_of?: string | null;
            /** @description Vrai si tous les montants ont pu être convertis (agrégat complet). */
            complete: boolean;
            /**
             * Format: int32
             * @description Nombre de montants effectivement convertis et inclus.
             */
            converted: number;
            /**
             * @description Devise du total (code ISO 4217).
             * @example EUR
             */
            currency: string;
            /**
             * Format: int32
             * @description Nombre de montants exclus faute de taux connu.
             */
            excluded: number;
            /**
             * @description Total converti dans la devise cible (chaîne décimale, précision exacte).
             * @example 142.50
             */
            total: string;
        };
        /**
         * @description Requête de création de compte (REQ-AUT-001).
         *
         *     Le mot de passe transite en clair sur le canal TLS puis est haché argon2id côté serveur ;
         *     il n'est jamais stocké en clair.
         */
        CreateAccountRequest: {
            /**
             * Format: email
             * @description Adresse e-mail du compte.
             * @example user@example.com
             */
            email: string;
            /**
             * Format: password
             * @description Mot de passe (longueur minimale vérifiée côté serveur, REQ-AUT-003).
             * @example correct horse battery staple
             */
            password: string;
        };
        /**
         * @description Requête d'appairage d'un appareil natif (REQ-AUT-005).
         *
         *     Comme l'authentification web, mais émet un jeton propre à l'appareil (corps de réponse) au lieu
         *     d'un cookie ; l'appareil fournit un libellé et sa plateforme.
         */
        CreateDeviceSessionRequest: {
            /**
             * Format: email
             * @description Adresse e-mail du compte.
             * @example user@example.com
             */
            email: string;
            /**
             * @description Libellé lisible de l'appareil (choisi par l'utilisateur ou dérivé du matériel).
             * @example MacBook de Léa
             */
            label: string;
            /**
             * Format: password
             * @description Mot de passe.
             */
            password: string;
            /**
             * @description Plateforme de l'appareil.
             * @example desktop
             */
            platform: string;
        };
        /** @description Requête d'authentification (REQ-AUT-002). */
        CreateSessionRequest: {
            /**
             * Format: email
             * @description Adresse e-mail du compte.
             * @example user@example.com
             */
            email: string;
            /**
             * Format: password
             * @description Mot de passe.
             */
            password: string;
        };
        /** @description Représentation du compte authentifié courant (REQ-AUT-002). */
        CurrentUser: {
            /** @description Adresse e-mail du compte courant. */
            email: string;
        };
        /**
         * @description Résumé d'un appareil appairé, pour la liste de gestion (REQ-AUT-006).
         *
         *     `id` (UUID) et `last_seen_at` (RFC 3339) sont sérialisés en chaînes pour rester indépendants des
         *     features `utoipa`/`chrono` ; `current` distingue l'appareil à l'origine de la requête courante.
         */
        DeviceSummary: {
            /** @description Vrai si cet appareil est celui qui a émis la requête courante. */
            current: boolean;
            /** @description Identifiant de l'appareil (UUID), clé de révocation. */
            id: string;
            /** @description Libellé lisible. */
            label: string;
            /** @description Dernière activité (horodatage RFC 3339). */
            last_seen_at: string;
            /** @description Plateforme de l'appareil. */
            platform: string;
        };
        /**
         * @description Jeton d'appareil émis à l'appairage (REQ-AUT-005).
         *
         *     Renvoyé **une seule fois** : la coquille native le stocke via `PlatformAdapter.secureStore`,
         *     jamais en clair côté serveur (seule son empreinte SHA-256 est conservée).
         */
        DeviceToken: {
            /** @description Jeton opaque à présenter en `Authorization: Bearer`. */
            token: string;
        };
        /** @description Réponse d'état du serveur. */
        HealthResponse: {
            /** @description Nom du service. */
            service: string;
            /** @description État. */
            status: string;
            /** @description Version semver. */
            version: string;
        };
        /**
         * @description Un montant en devise pour l'agrégation multi-devises (REQ-CUR-004).
         *
         *     `amount` est une **chaîne décimale** (règle R4 / REQ-CUR-002) : jamais un nombre JSON, qui
         *     introduirait une imprécision flottante sur un montant.
         */
        MoneyInput: {
            /**
             * @description Montant en chaîne décimale (ex. `"12.34"`).
             * @example 12.34
             */
            amount: string;
            /**
             * @description Code devise ISO 4217 (ex. `"EUR"`).
             * @example EUR
             */
            currency: string;
        };
        /**
         * @description Détail d'erreur conforme à la RFC 9457 (`application/problem+json`).
         *
         *     Schéma d'erreur unique de l'API : toute réponse d'erreur adopte ce format,
         *     sans jamais divulguer de trace d'exécution, de requête SQL ni de chemin de
         *     fichier (AGENTS.md §6, REQ-SEC-002).
         */
        Problem: {
            /** @description Explication spécifique à cette occurrence du problème. */
            detail?: string | null;
            /** @description URI de référence identifiant l'occurrence spécifique du problème. */
            instance?: string | null;
            /**
             * Format: int32
             * @description Code de statut HTTP généré par l'origine.
             */
            status: number;
            /** @description Résumé court et lisible du type de problème, stable pour un `type` donné. */
            title: string;
            /**
             * @description URI de référence identifiant le type de problème.
             * @example about:blank
             */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountRequest"];
            };
        };
        responses: {
            /** @description Compte créé — réponse identique que l'e-mail existe ou non */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Requête invalide */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    createDeviceSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDeviceSessionRequest"];
            };
        };
        responses: {
            /** @description Appareil appairé ; jeton d'appareil émis (corps) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceToken"];
                };
            };
            /** @description Identifiants invalides */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Trop de tentatives ; réessayer après l'en-tête Retry-After */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listDevices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Appareils appairés du foyer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceSummary"][];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    revokeDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant (UUID) de l'appareil à révoquer */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Appareil révoqué */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Appareil inconnu ou hors du foyer */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    aggregateConverted: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AggregateRequest"];
            };
        };
        responses: {
            /** @description Agrégat converti (éventuellement partiel) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConvertedTotalResponse"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Devise ou montant invalide */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Serveur opérationnel */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Compte courant */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Mot de passe changé ; autres sessions et jetons d'appareil invalidés */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Mot de passe actuel incorrect ; aucun changement */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Nouveau mot de passe non conforme */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Trop de tentatives ; réessayer après l'en-tête Retry-After */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Session ouverte ; cookie de session posé */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Identifiants invalides */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Trop de tentatives ; réessayer après l'en-tête Retry-After */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session invalidée (idempotent) ; cookie expiré */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
