/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** État de santé du serveur. */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Réponse d'état du serveur. */
        HealthResponse: {
            /** @description Nom du service. */
            service: string;
            /** @description État. */
            status: string;
            /** @description Version semver. */
            version: string;
        };
        /**
         * @description Détail d'erreur conforme à la RFC 9457 (`application/problem+json`).
         *
         *     Schéma d'erreur unique de l'API : toute réponse d'erreur adopte ce format,
         *     sans jamais divulguer de trace d'exécution, de requête SQL ni de chemin de
         *     fichier (AGENTS.md §6, REQ-SEC-002).
         */
        Problem: {
            /** @description Explication spécifique à cette occurrence du problème. */
            detail?: string | null;
            /** @description URI de référence identifiant l'occurrence spécifique du problème. */
            instance?: string | null;
            /**
             * Format: int32
             * @description Code de statut HTTP généré par l'origine.
             */
            status: number;
            /** @description Résumé court et lisible du type de problème, stable pour un `type` donné. */
            title: string;
            /**
             * @description URI de référence identifiant le type de problème.
             * @example about:blank
             */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Serveur opérationnel */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
